# Binance exchange info/symbols: https://api.binance.com/api/v1/exchangeInfo
# Binance exchange info/avg price: https://api.binance.com/api/v3/avgPrice?symbol=LDOUSDT

network_config_file = "https://raw.githubusercontent.com/vegaprotocol/networks-internal/main/stagnet1/vegawallet-stagnet1.toml"
debug = false
work_dir = "/opt/workdir"


[http_server]
interface = "0.0.0.0"
port = 80

[vegawallet]
version = "v0.74.0-preview.1" # ignored if auto_version == true
repository = "vegaprotocol/vega"
artifact_name = "vega"
download_wallet_binary = true
auto_version = true

wallet_name = "vegamarketsim"
network_name = "stagnet1"
binary = "vega" # vega binary, as we use vega wallet command
home = "/opt/wallets-mount/wallethome"
passphrase_file = "./assets/passphrase.txt"
tokens_file = "/opt/wallets-mount/wallet-info.json"
state_file = "/opt/wallets-mount/wallet-state.json"


[scenario.mainnet_simulation_btcusdt]
    market_name = "Bitcoin / Tether USD (Perpetual)"
    price_symbol = "BTCUSDT"
    price_source = "binance"
    step_length_seconds = 30
    [scenario.mainnet_simulation_btcusdt.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 1
        pdp = 4
    [scenario.mainnet_simulation_btcusdt.market_maker_args]
        market_kappa = 0.3
        market_order_arrival_rate = 150
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 1
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 150000
        initial_mint = 200000
    [scenario.mainnet_simulation_btcusdt.automated_market_maker_args]
        proposed_fee=0.0001
        lower_bound_scaling=0.9
        upper_bound_scaling=1.1
        leverage_at_lower_bound=2
        leverage_at_upper_bound=5
        update_bias=0.001
        slippage_tolerance=0.5
        commitment_amount=1000000000
        initial_mint=2000000000
    [scenario.mainnet_simulation_btcusdt.auction_trader_args]
        traders = 2
        initial_volume = 0.1
        initial_mint = 10000
    [scenario.mainnet_simulation_btcusdt.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 2000
    [scenario.mainnet_simulation_btcusdt.sensitive_trader_args]
        traders = 10
        scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
        max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
        initial_mint = 10000
    [scenario.mainnet_simulation_btcusdt.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.mainnet_simulation_injustd]
    market_name = "Injective / Tether USD (Perpetual)"
    price_symbol = "INJUSDT"
    price_source = "binance"
    step_length_seconds = 19
    [scenario.mainnet_simulation_injustd.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 3
        pdp = 1
    [scenario.mainnet_simulation_injustd.market_maker_args]
        market_kappa = 3000
        market_order_arrival_rate = 150
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 0.001
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 150000
        initial_mint = 200000
    [scenario.mainnet_simulation_injustd.automated_market_maker_args]
        proposed_fee=0.0001
        lower_bound_scaling=0.9
        upper_bound_scaling=1.1
        leverage_at_lower_bound=2
        leverage_at_upper_bound=5
        update_bias=0.001
        slippage_tolerance=0.5
        commitment_amount=1000000000
        initial_mint=2000000000
    [scenario.mainnet_simulation_injustd.auction_trader_args]
        traders = 2
        initial_volume = 2
        initial_mint = 10000
    [scenario.mainnet_simulation_injustd.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 2000
    [scenario.mainnet_simulation_injustd.sensitive_trader_args]
        traders = 10
        scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
        max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
         initial_mint = 10000
     [scenario.mainnet_simulation_injustd.simulation_args]
         n_steps = 99999999
         granularity = "MINUTE"
         coinbase_code = "BTC-USDT"
         start_date = "2022-11-01 00:00:00"
         randomise_history = false

# [scenario.mainnet_simulation_snxustd]
#     market_name = "Synthetix / Tether USD (Perpetual)"
#     binance_code = "SNXUSDT"
#     step_length_seconds = 9
#     [scenario.mainnet_simulation_snxustd.market_manager_args]
#         asset_name = "tUSDC"
#         adp = 6
#         mdp = 3
#         pdp = 1
#     [scenario.mainnet_simulation_snxustd.market_maker_args]
#         market_kappa = 30000
#         market_order_arrival_rate = 150
#         order_kappa = 0.15
#         order_size = 1
#         order_levels = 25
#         order_spacing = 0.001
#         order_clipping = 10000
#         inventory_lower_boundary = -3
#         inventory_upper_boundary = 3
#         fee_amount = 0.0001
#         commitment_amount = 15000
#         initial_mint = 20000
#     [scenario.mainnet_simulation_snxustd.auction_trader_args]
#         traders = 2
#         initial_volume = 1
#         initial_mint = 10000
#     [scenario.mainnet_simulation_snxustd.random_trader_args]
#         traders = 10
#         order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#         order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
#         step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
#         initial_mint = 2000
#     [scenario.mainnet_simulation_snxustd.sensitive_trader_args]
#         traders = 10
#         scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
#         max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
#         initial_mint = 10000
#     [scenario.mainnet_simulation_snxustd.simulation_args]
#         n_steps = 99999999
#         granularity = "MINUTE"
#         coinbase_code = "BTC-USDT"
#         start_date = "2022-11-01 00:00:00"
#         randomise_history = false
# 
# [scenario.mainnet_simulation_ldoustd]
#     market_name = "Lido / Tether USD (Perpetual)"
#     binance_code = "LDOUSDT"
#     step_length_seconds = 16
#     [scenario.mainnet_simulation_ldoustd.market_manager_args]
#         asset_name = "tUSDC"
#         adp = 6
#         mdp = 4
#         pdp = 1
#     [scenario.mainnet_simulation_ldoustd.market_maker_args]
#         market_kappa = 30000
#         market_order_arrival_rate = 150
#         order_kappa = 0.15
#         order_size = 1
#         order_levels = 25
#         order_spacing = 0.001
#         order_clipping = 10000
#         inventory_lower_boundary = -3
#         inventory_upper_boundary = 3
#         fee_amount = 0.0001
#         commitment_amount = 150000
#         initial_mint = 200000
#     [scenario.mainnet_simulation_ldoustd.auction_trader_args]
#         traders = 2
#         initial_volume = 1
#         initial_mint = 10000
#     [scenario.mainnet_simulation_ldoustd.random_trader_args]
#         traders = 10
#         order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#         order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
#         step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
#         initial_mint = 2000
#     [scenario.mainnet_simulation_ldoustd.sensitive_trader_args]
#         traders = 10
#         scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
#         max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
#         initial_mint = 10000
#     [scenario.mainnet_simulation_ldoustd.simulation_args]
#         n_steps = 99999999
#         granularity = "MINUTE"
#         coinbase_code = "BTC-USDT"
#         start_date = "2022-11-01 00:00:00"
#         randomise_history = false

[scenario.mainnet_simulation_ethustd]
    market_name = "Ether / Tether USD (Perpetual)"
    price_symbol = "ETHUSDT"
    price_source = "binance"
    step_length_seconds = 16
    [scenario.mainnet_simulation_ethustd.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 2
        pdp = 3
    [scenario.mainnet_simulation_ethustd.market_maker_args]
        market_kappa = 9.15
        market_order_arrival_rate = 100
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 1
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 150000
        initial_mint = 600000
    [scenario.mainnet_simulation_ethustd.automated_market_maker_args]
        proposed_fee=0.0001
        lower_bound_scaling=0.9
        upper_bound_scaling=1.1
        leverage_at_lower_bound=2
        leverage_at_upper_bound=5
        update_bias=0.001
        slippage_tolerance=0.5
        commitment_amount=1000000000
        initial_mint=2000000000
    [scenario.mainnet_simulation_ethustd.auction_trader_args]
        initial_volume = 0.001
        initial_mint = 10000
    [scenario.mainnet_simulation_ethustd.random_trader_args]
        order_intensity = [45, 45, 45]
        order_volume = [0.01, 0.1, 1.0]
        step_bias = [0.333, 0.012, 0.003]
        initial_mint = 1000000
    [scenario.mainnet_simulation_ethustd.sensitive_trader_args]
        scale = [10, 10, 10]
        max_order_size = [0.001, 0.01, 0.1]
        initial_mint = 10000
    [scenario.mainnet_simulation_ethustd.simulation_args]
        n_steps = -1
        granularity = "MINUTE"
        coinbase_code = "ETH-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.dogepoint]
    market_name = "Doge Points / USDT (Futures market)"
    price_symbol = "DOGEUSDT"
    price_source = "binance"
    step_length_seconds = 1
    [scenario.dogepoint.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 5
        pdp = -2
    [scenario.dogepoint.market_maker_args]
        market_kappa = 100000
        market_order_arrival_rate = 150
        order_kappa = 3
        order_size = 1
        order_levels = 25
        order_spacing = 0.00005
        order_clipping = 200000
        inventory_lower_boundary = -500
        inventory_upper_boundary = 500
        fee_amount = 0.0001
        commitment_amount = 3000000
        initial_mint = 40000000
    [scenario.dogepoint.automated_market_maker_args]
        proposed_fee=0.0001
        lower_bound_scaling=0.9
        upper_bound_scaling=1.1
        leverage_at_lower_bound=2
        leverage_at_upper_bound=5
        update_bias=0.001
        slippage_tolerance=0.5
        commitment_amount=1000000000
        initial_mint=2000000000
    [scenario.dogepoint.auction_trader_args]
        traders = 2
        initial_volume = 100
        initial_mint = 100000
    [scenario.dogepoint.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [100, 150, 180, 200, 260, 280, 300, 350, 400, 500, 550] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.dogepoint.sensitive_trader_args]
        traders = 10
        scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
        max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
        initial_mint = 100000
    [scenario.dogepoint.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.dogepoint2]
    market_name = "Doge Points 2 / USDT (Futures market)"
    price_symbol = "DOGEUSDT"
    price_source = "binance"
    step_length_seconds = 1
    [scenario.dogepoint2.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 5
        pdp = -2
    [scenario.dogepoint2.market_maker_args]
        market_kappa = 100000
        market_order_arrival_rate = 150
        order_kappa = 3
        order_size = 1
        order_levels = 25
        order_spacing = 0.00005
        order_clipping = 200000
        inventory_lower_boundary = -500
        inventory_upper_boundary = 500
        fee_amount = 0.0001
        commitment_amount = 3000000
        initial_mint = 40000000
    [scenario.dogepoint2.automated_market_maker_args]
        proposed_fee=0.0001
        lower_bound_scaling=0.9
        upper_bound_scaling=1.1
        leverage_at_lower_bound=2
        leverage_at_upper_bound=5
        update_bias=0.001
        slippage_tolerance=0.5
        commitment_amount=1000000000
        initial_mint=2000000000
    [scenario.dogepoint2.auction_trader_args]
        traders = 2
        initial_volume = 100
        initial_mint = 100000
    [scenario.dogepoint2.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [100, 150, 180, 200, 260, 280, 300, 350, 400, 500, 550] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.dogepoint2.sensitive_trader_args]
        traders = 10
        scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
        max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
        initial_mint = 100000
    [scenario.dogepoint2.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

# 
# [scenario.spot_market]
#     market_name = "Bitcoin / Tether USD (Spot)"
#     binance_code = "BTCUSDT"
#     step_length_seconds = 20
#     [scenario.spot_market.market_manager_args]
#         asset_name = "tUSDC" # tBTC
#         quote_asset_name = "tUSDC"
#         adp = 6
#         mdp = 1
#         pdp = 0
#     [scenario.spot_market.market_maker_args]
#         market_kappa = 0.3
#         market_order_arrival_rate = 600
#         order_kappa = 0.15
#         order_size = 1
#         order_levels = 25
#         order_spacing = 1
#         order_clipping = 10000
#         inventory_lower_boundary = -3
#         inventory_upper_boundary = 3
#         fee_amount = 0.0001
#         commitment_amount = 650000
#         initial_mint = 2200000
#     [scenario.spot_market.auction_trader_args]
#         traders = 2
#         initial_volume = 0.1
#         initial_mint = 100000
#     [scenario.spot_market.random_trader_args]
#         traders = 10
#         order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#         order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
#         step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
#         initial_mint = 20000
#     [scenario.spot_market.sensitive_trader_args]
#         traders = 10
#         scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
#         max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
#         initial_mint = 100000
#     [scenario.spot_market.simulation_args]
#         n_steps = 99999999
#         granularity = "MINUTE"
#         coinbase_code = "BTC-USDT"
#         start_date = "2022-11-01 00:00:00"
#         randomise_history = false


[scenario.pepe1000]
    market_name = "PEPE / USD (price*1000)(Perpetual)"
    price_symbol = "PEPEUSDT"
    price_source = "binance"
    feed_price_multiplier = 1000
    step_length_seconds = 30
    [scenario.pepe1000.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 7
        pdp = -3
    [scenario.pepe1000.market_maker_args]
        market_kappa = 400000
        market_order_arrival_rate = 1500
        order_kappa = 0.5
        order_size = 100
        order_levels = 25
        order_spacing = 0.00005
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.05
        commitment_amount = 2500000
        initial_mint = 5500000
    [scenario.pepe1000.automated_market_maker_args]
        proposed_fee=0.0001
        lower_bound_scaling=0.9
        upper_bound_scaling=1.1
        leverage_at_lower_bound=2
        leverage_at_upper_bound=5
        update_bias=0.001
        slippage_tolerance=0.5
        commitment_amount=1000000000
        initial_mint=2000000000
    [scenario.pepe1000.auction_trader_args]
        traders = 2
        initial_volume = 10000
        initial_mint = 10000
    [scenario.pepe1000.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [1000.0, 5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0, 160000.0, 180000.0] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.pepe1000.sensitive_trader_args]
        traders = 0
        scale = [0.2, 0.4, 0.6, 0.8, 0.10, 0.12, 0.14, 0.16, 0.17, 0.20]
        max_order_size = [1000.0,  5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0]
        initial_mint = 10000
    [scenario.pepe1000.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false
