Name = "stagnet1"
Level = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API.GRPC]
  Hosts = [
    "n03.s.vega.xyz:3007"
  ]
  Retries = 5

[API.REST]
  Hosts = [
    "https://n03.s.vega.xyz"
  ]

[API.GraphQL]
  Hosts = [
    "https://n03.s.vega.xyz/query",
  ]

[Console]
  URL = "staging.vega.trading"
  LocalPort = 1847

[TokenDApp]
  URL = "staging.token.vega.xyz"
  LocalPort = 1848
