FileVersion = 2

Name = "stagnet1"

[[Metadata]]
key = "network"
name = "stagnet1"

[API]

  [API.GRPC]
    Hosts = ["api.stagnet1.vega.xyz:3007", "api.n05.stagnet1.vega.xyz:3007", "api.n06.stagnet1.vega.xyz:3007"]
    Retries = 5

  [API.GraphQL]
    Hosts = ["https://api.stagnet1.vega.xyz/graphql", "https://api.n05.stagnet1.vega.xyz/graphql", "https://api.n06.stagnet1.vega.xyz/graphql"]

  [API.REST]
    Hosts = ["https://api.stagnet1.vega.xyz", "https://api.n05.stagnet1.vega.xyz", "https://api.n06.stagnet1.vega.xyz"]

[Apps]
  Console = "https://stagnet1.console.vega.xyz"
  TokenDApp = "https://stagnet1.governance.vega.xyz"
  Explorer = "https://stagnet1.explorer.vega.xyz"
