network_config_file = "https://raw.githubusercontent.com/vegaprotocol/networks-internal/main/mainnet-mirror/vegawallet-mainnet-mirror.toml"
debug = false
work_dir = "./network"



[http_server]
interface = "0.0.0.0"
port = 80

[vegawallet]
version = "" # ignored if auto_version == true
repository = "vegaprotocol/vega"
artifact_name = "vega"
download_wallet_binary = true
auto_version = true

wallet_name = "vegamarketsim"
network_name = "mainnet-mirror"
binary = "vega" # vega binary, as we use vega wallet command
home = "/opt/wallets-mount/wallethome"
passphrase_file = "./assets/passphrase.txt"
tokens_file = "/opt/wallets-mount/wallet-info.json"
state_file = "/opt/wallets-mount/wallet-state.json"



[scenario.pepe1000]
    market_name = "1000 PEPE / Tether USD (Perpetual)"
    price_symbol = "PEPEUSDT"
    price_source = "binance"
    feed_price_multiplier = 1000
    step_length_seconds = 30
    [scenario.pepe1000.market_manager_args]
        asset_name = "USDT"
        adp = 6
        mdp = 5
        pdp = 1
    [scenario.pepe1000.market_maker_args]
        market_kappa = 400000
        market_order_arrival_rate = 1500
        order_kappa = 0.5
        order_size = 100
        order_levels = 25
        order_spacing = 0.00005
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.025
        commitment_amount = 2500000
        initial_mint = 5500000
    [scenario.pepe1000.auction_trader_args]
        traders = 2
        initial_volume = 10000
        initial_mint = 10000
    [scenario.pepe1000.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [1000.0, 5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0, 160000.0, 180000.0] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.pepe1000.sensitive_trader_args]
        traders = 0
        scale = [0.2, 0.4, 0.6, 0.8, 0.10, 0.12, 0.14, 0.16, 0.17, 0.20]
        max_order_size = [1000.0,  5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0]
        initial_mint = 10000
    [scenario.pepe1000.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false


[scenario.eth_usdt_arb_usdt]
    market_name = "Ethereum Tether USD / Arbitrum Tether USD  (Spot)"
    price_symbol = "USDTDAI"
    price_source = "binance"
    feed_price_multiplier = 1
    step_length_seconds = 5
    [scenario.eth_usdt_arb_usdt.market_manager_args]
        asset_name = "USDTT"
        quote_asset_name = "USDT"
        adp = 6
        mdp = 5
        pdp = 1
    [scenario.eth_usdt_arb_usdt.market_maker_args]
        market_kappa = 400000
        market_order_arrival_rate = 1500
        order_kappa = 0.5
        order_size = 100
        order_levels = 25
        order_spacing = 0.00005
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.025
        commitment_amount = 2500000
        initial_mint = 5500000
    [scenario.eth_usdt_arb_usdt.auction_trader_args]
        traders = 2
        initial_volume = 10000
        initial_mint = 10000
    [scenario.eth_usdt_arb_usdt.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [1000.0, 5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0, 160000.0, 180000.0] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.eth_usdt_arb_usdt.sensitive_trader_args]
        traders = 0
        scale = [0.2, 0.4, 0.6, 0.8, 0.10, 0.12, 0.14, 0.16, 0.17, 0.20]
        max_order_size = [1000.0,  5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0]
        initial_mint = 10000
    [scenario.eth_usdt_arb_usdt.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.vega_usdt]
    market_name = "Vega / Tether USD (Spot)"
    price_symbol = "SYNUSDT"
    price_source = "binance"
    feed_price_multiplier = 1
    step_length_seconds = 5
    [scenario.vega_usdt.market_manager_args]
        asset_name = "VEGA"
        quote_asset_name = "USDT"
        adp = 6
        mdp = 5
        pdp = 1
    [scenario.vega_usdt.market_maker_args]
        market_kappa = 30000
        market_order_arrival_rate = 1500
        order_kappa = 55
        order_size = 10
        order_levels = 30
        order_spacing = 0.002
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.025
        commitment_amount = 120000
        initial_mint = 120000
    [scenario.vega_usdt.auction_trader_args]
        traders = 2
        initial_volume = 10000
        initial_mint = 10000
    [scenario.vega_usdt.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [0.01, 0.05, 0.10, 0.20, 0.40, 0.60, 0.80, 1.0, 1.2, 1.4, 1.6, 1.8] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.vega_usdt.sensitive_trader_args]
        traders = 10
        scale = [0.01, 0.04, 0.06, 0.08, 0.001, 0.0012, 0.0014, 0.0016, 0.0017, 0.0020]
        max_order_size = [0.1, 0.2, 0.25, 0.33, 0.35, 0.09, 0.08, 0.05, 0.03, 0.01]
        initial_mint = 4500
    [scenario.vega_usdt.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.neon_usdt]
    market_name = "Neon EVM / Tether USD (Perpetual)"
    price_symbol = "SFPUSDT"
    price_source = "binance"
    feed_price_multiplier = 1
    step_length_seconds = 5
    [scenario.neon_usdt.market_manager_args]
        asset_name = "USDT"
        adp = 6
        mdp = 5
        pdp = 1
    [scenario.neon_usdt.market_maker_args]
        market_kappa = 400000
        market_order_arrival_rate = 1500
        order_kappa = 0.5
        order_size = 100
        order_levels = 25
        order_spacing = 0.00005
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.025
        commitment_amount = 2500000
        initial_mint = 5500000
    [scenario.neon_usdt.auction_trader_args]
        traders = 2
        initial_volume = 100
        initial_mint = 100
    [scenario.neon_usdt.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [1, 2, 4, 6, 8, 10, 16, 20, 32, 38, 41, 50] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.neon_usdt.sensitive_trader_args]
        traders = 0
        scale = [0.2, 0.4, 0.6, 0.8, 0.10, 0.12, 0.14, 0.16, 0.17, 0.20]
        max_order_size = [1000.0,  5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0]
        initial_mint = 10000
    [scenario.neon_usdt.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.meme_top5]
    market_name = "Meme top 5 / Tether USD (Perpetual)"
    price_symbol = "MEME5/USD"
    price_source = "pyth"
    feed_price_multiplier = 1
    step_length_seconds = 5
    [scenario.meme_top5.market_manager_args]
        asset_name = "USDT"
        adp = 6
        mdp = 5
        pdp = 1
    [scenario.meme_top5.market_maker_args]
        market_kappa = 400000
        market_order_arrival_rate = 1500
        order_kappa = 0.5
        order_size = 100
        order_levels = 25
        order_spacing = 0.00005
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.025
        commitment_amount = 2500000
        initial_mint = 5500000
    [scenario.meme_top5.auction_trader_args]
        traders = 2
        initial_volume = 10000
        initial_mint = 10000
    [scenario.meme_top5.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 340] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.meme_top5.sensitive_trader_args]
        traders = 0
        scale = [0.2, 0.4, 0.6, 0.8, 0.10, 0.12, 0.14, 0.16, 0.17, 0.20]
        max_order_size = [1000.0,  5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0]
        initial_mint = 10000
    [scenario.meme_top5.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.XAU]
    market_name = "Gold / Tether USD (Perpetual)"
    price_symbol = "MKRUSDT"
    price_source = "binance"
    feed_price_multiplier = 1
    step_length_seconds = 5
    [scenario.XAU.market_manager_args]
        asset_name = "USDT"
        adp = 6
        mdp = 5
        pdp = 1
    [scenario.XAU.market_maker_args]
        market_kappa = 4000
        market_order_arrival_rate = 1500
        order_kappa = 0.5
        order_size = 100
        order_levels = 25
        order_spacing = 0.5
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.025
        commitment_amount = 2500000
        initial_mint = 5500000
    [scenario.XAU.auction_trader_args]
        traders = 2
        initial_volume = 10000
        initial_mint = 10000
    [scenario.XAU.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.4] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.XAU.sensitive_trader_args]
        traders = 0
        scale = [0.2, 0.4, 0.6, 0.8, 0.10, 0.12, 0.14, 0.16, 0.17, 0.20]
        max_order_size = [1000.0,  5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0]
        initial_mint = 10000
    [scenario.XAU.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false
