# Binance exchange info/symbols: https://api.binance.com/api/v1/exchangeInfo

network_config_file = "https://raw.githubusercontent.com/vegaprotocol/networks-internal/main/devnet1/vegawallet-devnet1.toml"
debug = false
work_dir = "/opt/workdir"


[http_server]
interface = "0.0.0.0"
port = 80

[vegawallet]
version = "v0.72.1-13391-08069ba0" # ignored if auto_version == true
repository = "vegaprotocol/vega-dev-releases"
artifact_name = "vega"
download_wallet_binary = true
auto_version = false

wallet_name = "vegamarketsim"
network_name = "devnet1"
binary = "vega" # vega binary, as we use vega wallet command
home = "/opt/wallets-mount/wallethome"
passphrase_file = "./assets/passphrase.txt"
tokens_file = "/opt/wallets-mount/wallet-info.json"
state_file = "/opt/wallets-mount/wallet-state.json"


[scenario.mainnet_simulation_btcusdt]
    market_name = "Bitcoin / Tether USD (Perpetual)"
    binance_code = "BTCUSDT"
    step_length_seconds = 30
    [scenario.mainnet_simulation_btcusdt.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 1
        pdp = 4
    [scenario.mainnet_simulation_btcusdt.market_maker_args]
        market_kappa = 0.3
        market_order_arrival_rate = 150
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 1
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 150000
        initial_mint = 200000
    [scenario.mainnet_simulation_btcusdt.auction_trader_args]
        traders = 2
        initial_volume = 0.1
        initial_mint = 10000
    [scenario.mainnet_simulation_btcusdt.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 2000
    [scenario.mainnet_simulation_btcusdt.sensitive_trader_args]
        traders = 10
        scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
        max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
        initial_mint = 10000
    [scenario.mainnet_simulation_btcusdt.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.mainnet_simulation_ethustd]
    market_name = "Ether / Tether USD (Perpetual)"
    binance_code = "ETHUSDT"
    step_length_seconds = 16
    [scenario.mainnet_simulation_ethustd.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 2
        pdp = 3
    [scenario.mainnet_simulation_ethustd.market_maker_args]
        market_kappa = 9.15
        market_order_arrival_rate = 100
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 1
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 100
        initial_mint = 600000
    [scenario.mainnet_simulation_ethustd.auction_trader_args]
        initial_volume = 0.001
        initial_mint = 10000
    [scenario.mainnet_simulation_ethustd.random_trader_args]
        order_intensity = [45, 45, 45]
        order_volume = [0.01, 0.1, 1.0]
        step_bias = [0.333, 0.012, 0.003]
        initial_mint = 1000000
    [scenario.mainnet_simulation_ethustd.sensitive_trader_args]
        scale = [10, 10, 10]
        max_order_size = [0.001, 0.01, 0.1]
        initial_mint = 10000
    [scenario.mainnet_simulation_ethustd.simulation_args]
        n_steps = -1
        granularity = "MINUTE"
        coinbase_code = "ETH-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.btcusdt_future]
    market_name = "BTC/USDT FUTURE"
    binance_code = "BTCUSDT"
    step_length_seconds = 30
    [scenario.btcusdt_future.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 1
        pdp = 4
    [scenario.btcusdt_future.market_maker_args]
        market_kappa = 0.3
        market_order_arrival_rate = 150
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 1
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 150000
        initial_mint = 200000
    [scenario.btcusdt_future.auction_trader_args]
        traders = 2
        initial_volume = 0.1
        initial_mint = 10000
    [scenario.btcusdt_future.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 2000
    [scenario.btcusdt_future.sensitive_trader_args]
        traders = 10
        scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
        max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
        initial_mint = 10000
    [scenario.btcusdt_future.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.ethusdt_future]
    market_name = "ETH/USDT Future"
    binance_code = "ETHUSDT"
    step_length_seconds = 16
    [scenario.ethusdt_future.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 2
        pdp = 3
    [scenario.ethusdt_future.market_maker_args]
        market_kappa = 9.15
        market_order_arrival_rate = 100
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 1
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 100
        initial_mint = 600000
    [scenario.ethusdt_future.auction_trader_args]
        initial_volume = 0.001
        initial_mint = 10000
    [scenario.ethusdt_future.random_trader_args]
        order_intensity = [45, 45, 45]
        order_volume = [0.01, 0.1, 1.0]
        step_bias = [0.333, 0.012, 0.003]
        initial_mint = 1000000
    [scenario.ethusdt_future.sensitive_trader_args]
        scale = [10, 10, 10]
        max_order_size = [0.001, 0.01, 0.1]
        initial_mint = 10000
    [scenario.ethusdt_future.simulation_args]
        n_steps = -1
        granularity = "MINUTE"
        coinbase_code = "ETH-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.mainnet_simulation_snxustd]
    market_name = "SNX/USDT-Perp"
    binance_code = "SNXUSDT"
    step_length_seconds = 9
    [scenario.mainnet_simulation_snxustd.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 3
        pdp = 1
    [scenario.mainnet_simulation_snxustd.market_maker_args]
        market_kappa = 30000
        market_order_arrival_rate = 150
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 0.001
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 150000
        initial_mint = 200000
    [scenario.mainnet_simulation_snxustd.auction_trader_args]
        traders = 2
        initial_volume = 1
        initial_mint = 10000
    [scenario.mainnet_simulation_snxustd.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 2000
    [scenario.mainnet_simulation_snxustd.sensitive_trader_args]
        traders = 10
        scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
        max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
        initial_mint = 10000
    [scenario.mainnet_simulation_snxustd.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.mainnet_simulation_ldoustd]
    market_name = "LDO/USDT-Perp"
    binance_code = "LDOUSDT"
    step_length_seconds = 16
    [scenario.mainnet_simulation_ldoustd.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 4
        pdp = 1
    [scenario.mainnet_simulation_ldoustd.market_maker_args]
        market_kappa = 30000
        market_order_arrival_rate = 150
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 0.001
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 150000
        initial_mint = 200000
    [scenario.mainnet_simulation_ldoustd.auction_trader_args]
        traders = 2
        initial_volume = 1
        initial_mint = 10000
    [scenario.mainnet_simulation_ldoustd.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 2000
    [scenario.mainnet_simulation_ldoustd.sensitive_trader_args]
        traders = 10
        scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
        max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
        initial_mint = 10000
    [scenario.mainnet_simulation_ldoustd.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.mainnet_simulation_injustd]
    market_name = "INJ/USDT-Perp"
    binance_code = "INJUSDT"
    step_length_seconds = 19
    [scenario.mainnet_simulation_injustd.market_manager_args]
        asset_name = "tUSDC"
        adp = 6
        mdp = 3
        pdp = 1
    [scenario.mainnet_simulation_injustd.market_maker_args]
        market_kappa = 3000
        market_order_arrival_rate = 150
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 0.001
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 150000
        initial_mint = 200000
    [scenario.mainnet_simulation_injustd.auction_trader_args]
        traders = 2
        initial_volume = 2
        initial_mint = 10000
    [scenario.mainnet_simulation_injustd.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 2000
    [scenario.mainnet_simulation_injustd.sensitive_trader_args]
        traders = 10
        scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
        max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
        initial_mint = 10000
    [scenario.mainnet_simulation_injustd.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false