# Binance exchange info/symbols: https://api.binance.com/api/v1/exchangeInfo

network_config_file = "https://raw.githubusercontent.com/vegaprotocol/networks-internal/main/fairground/vegawallet-fairground.toml"
debug = false
work_dir = "/opt/workdir"


[http_server]
interface = "0.0.0.0"
port = 80

[vegawallet]
version = "" # ignored if auto_version == true
repository = "vegaprotocol/vega"
artifact_name = "vega"
download_wallet_binary = true
auto_version = true

wallet_name = "vegamarketsim"
network_name = "fairground"
binary = "vega" # vega binary, as we use vega wallet command
home = "/opt/wallets-mount/wallethome"
passphrase_file = "./assets/passphrase.txt"
tokens_file = "/opt/wallets-mount/wallet-info.json"
state_file = "/opt/wallets-mount/wallet-state.json"

[scenario.mainnet_simulation_injustd]
     market_name = "Injective / Tether USD (Perpetual)"
     price_symbol = "INJUSDT"
     price_source = "binance"
     step_length_seconds = 19
     [scenario.mainnet_simulation_injustd.market_manager_args]
         asset_name = "Tether USD"
         adp = 6
         mdp = 3
         pdp = 1
     [scenario.mainnet_simulation_injustd.market_maker_args]
         market_kappa = 3000
         market_order_arrival_rate = 150
         order_kappa = 0.15
         order_size = 1
         order_levels = 25
         order_spacing = 0.001
         order_clipping = 10000
         inventory_lower_boundary = -3
         inventory_upper_boundary = 3
         fee_amount = 0.0001
         commitment_amount = 150000
         initial_mint = 200000
     [scenario.mainnet_simulation_injustd.auction_trader_args]
         traders = 2
         initial_volume = 2
         initial_mint = 10000
     [scenario.mainnet_simulation_injustd.random_trader_args]
         traders = 10
         order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
         order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
         step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
         initial_mint = 2000
     [scenario.mainnet_simulation_injustd.sensitive_trader_args]
         traders = 10
         scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
         max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
         initial_mint = 10000
     [scenario.mainnet_simulation_injustd.simulation_args]
         n_steps = 99999999
         granularity = "MINUTE"
         coinbase_code = "BTC-USDT"
         start_date = "2022-11-01 00:00:00"
         randomise_history = false# 

[scenario.incentive_btcusdt]
    market_name = "tBitcoin / USDT (Spot)"
    price_symbol = "BTCUSDT"
    price_source = "binance"
    step_length_seconds = 20
    [scenario.incentive_btcusdt.market_manager_args]
        asset_name = "Tether USD" # BTC
        quote_asset_name = "USDT"
    [scenario.incentive_btcusdt.market_maker_args]
        market_kappa = 3.9
        market_order_arrival_rate = 600
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 1
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 650000
        initial_mint = 2200000
    [scenario.incentive_btcusdt.auction_trader_args]
        traders = 2
        initial_volume = 0.1
        initial_mint = 100000
    [scenario.incentive_btcusdt.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18] # 
       step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.incentive_btcusdt.sensitive_trader_args]
       traders = 10
        scale = [2, 4, 6, 8, 10, 12, 14, 16, 17, 20]
        max_order_size = [0.001, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14]
        initial_mint = 100000
    [scenario.incentive_btcusdt.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.pepe1000]
    market_name = "PEPE / USD (price*1000)(Perpetual)"
    price_symbol = "PEPEUSDT"
    price_source = "binance"
    feed_price_multiplier = 1000
    step_length_seconds = 30
    [scenario.pepe1000.market_manager_args]
        asset_name = "USD PEPENING 2"
        adp = 6
        mdp = 7
        pdp = -3
    [scenario.pepe1000.market_maker_args]
        market_kappa = 400000
        market_order_arrival_rate = 1500
        order_kappa = 0.5
        order_size = 100
        order_levels = 25
        order_spacing = 0.00005
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.025
        commitment_amount = 2500000
        initial_mint = 5500000
    [scenario.pepe1000.auction_trader_args]
        traders = 2
        initial_volume = 10000
        initial_mint = 10000
    [scenario.pepe1000.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [1000.0, 5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0, 160000.0, 180000.0] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.pepe1000.sensitive_trader_args]
        traders = 0
        scale = [0.2, 0.4, 0.6, 0.8, 0.10, 0.12, 0.14, 0.16, 0.17, 0.20]
        max_order_size = [1000.0,  5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0]
        initial_mint = 10000
    [scenario.pepe1000.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.usdtusdt]
    market_name = "Ethereum Tether USD / Arbitrum Tether USD  (Spot)"
    price_symbol = "USDCUSDT"
    price_source = "binance"
    feed_price_multiplier = 1
    step_length_seconds = 30    
    [scenario.usdtusdt.market_manager_args]
        asset_name = "Tether USD"
        adp = 6
        mdp = 7
        pdp = -3
    [scenario.usdtusdt.market_maker_args]
        market_kappa = 400000
        market_order_arrival_rate = 1500
        order_kappa = 0.5
        order_size = 100
        order_levels = 25
        order_spacing = 0.00005
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.025
        commitment_amount = 2500000
        initial_mint = 5500000
    [scenario.usdtusdt.auction_trader_args]
        traders = 2
        initial_volume = 10000
        initial_mint = 10000
    [scenario.usdtusdt.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [1000.0, 5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0, 160000.0, 180000.0] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.usdtusdt.sensitive_trader_args]
        traders = 0
        scale = [0.2, 0.4, 0.6, 0.8, 0.10, 0.12, 0.14, 0.16, 0.17, 0.20]
        max_order_size = [1000.0,  5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0]
        initial_mint = 10000
    [scenario.usdtusdt.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.XAU]
    market_name = "Gold / Tether USD (Perpetual)"
    price_symbol = "XAU/USD"
    price_source = "pyth"
    feed_price_multiplier = 1
    step_length_seconds = 5
    [scenario.XAU.market_manager_args]
        asset_name = "USDT"
        adp = 6
        mdp = 5
        pdp = 1
    [scenario.XAU.market_maker_args]
        market_kappa = 4000
        market_order_arrival_rate = 1500
        order_kappa = 0.5
        order_size = 0.1
        order_levels = 25
        order_spacing = 0.5
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.025
        commitment_amount = 2500000
        initial_mint = 5500000
    [scenario.XAU.auction_trader_args]
        traders = 2
        initial_volume = 10000
        initial_mint = 10000
    [scenario.XAU.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.4] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.XAU.sensitive_trader_args]
        traders = 0
        scale = [0.2, 0.4, 0.6, 0.8, 0.10, 0.12, 0.14, 0.16, 0.17, 0.20]
        max_order_size = [1000.0,  5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0]
        initial_mint = 10000
    [scenario.XAU.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false

[scenario.EUR]
    market_name = "Euro / Tether USD (Perpetual)"
    price_symbol = "EUR/USD"
    price_source = "pyth"
    feed_price_multiplier = 1
    step_length_seconds = 5
    [scenario.EUR.market_manager_args]
        asset_name = "USDT"
        adp = 6
        mdp = 5
        pdp = 1
    [scenario.EUR.market_maker_args]
        market_kappa = 400
        market_order_arrival_rate = 1500
        order_kappa = 0.5
        order_size = 100
        order_levels = 25
        order_spacing = 0.5
        order_clipping = 0.0001
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.025
        commitment_amount = 2500000
        initial_mint = 5500000
    [scenario.EUR.auction_trader_args]
        traders = 2
        initial_volume = 10000
        initial_mint = 10000
    [scenario.EUR.random_trader_args]
        traders = 10
        order_intensity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        order_volume = [1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.4] # 
        step_bias = [0.111, 0.95, 0.50, 0.48, 0.08, 0.06, 0.05, 0.03, 0.012, 0.008, 0.006]
        initial_mint = 20000
    [scenario.EUR.sensitive_trader_args]
        traders = 0
        scale = [0.2, 0.4, 0.6, 0.8, 0.10, 0.12, 0.14, 0.16, 0.17, 0.20]
        max_order_size = [1000.0,  5000.0, 10000.0, 20000.0, 40000.0, 60000.0, 80000.0, 100000.0, 120000.0, 140000.0]
        initial_mint = 10000
    [scenario.EUR.simulation_args]
        n_steps = 99999999
        granularity = "MINUTE"
        coinbase_code = "BTC-USDT"
        start_date = "2022-11-01 00:00:00"
        randomise_history = false
