Name = "fairground"

[[Metadata]]
key = "network"
name = "fairground"

[API]

  [API.GRPC]
    Hosts = ["api.n06.testnet.vega.xyz:3007", "api.n07.testnet.vega.xyz:3007", "api.n08.testnet.vega.xyz:3007", "api.n09.testnet.vega.xyz:3007", "api.n10.testnet.vega.xyz:3007", "api.n11.testnet.vega.xyz:3007", "api.n12.testnet.vega.xyz:3007"]
    Retries = 5

  [API.GraphQL]
    Hosts = ["https://api.n06.testnet.vega.xyz/graphql", "https://api.n07.testnet.vega.xyz/graphql", "https://api.n08.testnet.vega.xyz/graphql", "https://api.n09.testnet.vega.xyz/graphql", "https://api.n10.testnet.vega.xyz/graphql", "https://api.n11.testnet.vega.xyz/graphql", "https://api.n12.testnet.vega.xyz/graphql"]

  [API.REST]
    Hosts = ["https://api.n06.testnet.vega.xyz", "https://api.n07.testnet.vega.xyz", "https://api.n08.testnet.vega.xyz", "https://api.n09.testnet.vega.xyz", "https://api.n10.testnet.vega.xyz", "https://api.n11.testnet.vega.xyz", "https://api.n12.testnet.vega.xyz"]

[Apps]
  Console = "console.fairground.wtf"
  TokenDApp = "token.fairground.wtf"
  Explorer = "explorer.fairground.wtf"
