FileVersion = 2

Name = "fairground"

[[Metadata]]
key = "network"
name = "fairground"

[API]

  [API.GRPC]
    Hosts = ["api.n06.testnet.vega.xyz:3007", "api.n07.testnet.vega.xyz:3007"]
    Retries = 5

  [API.GraphQL]
    Hosts = ["https://api.n06.testnet.vega.xyz/graphql", "https://api.n07.testnet.vega.xyz/graphql"]

  [API.REST]
    Hosts = ["https://api.n06.testnet.vega.xyz", "https://api.n07.testnet.vega.xyz"]

[Apps]
  Console = "console.fairground.wtf"
  TokenDApp = "token.fairground.wtf"
  Explorer = "explorer.fairground.wtf"
