Host = "127.0.0.1"
Level = "info"
Name = "fairground"
Port = 1789
TokenExpiry = "168h0m0s"

[API]

  [API.GRPC]
    Hosts = ["api.testnet.vega.xyz:3007", "api.n00.testnet.vega.xyz:3007", "api.n06.testnet.vega.xyz:3007", "api.n07.testnet.vega.xyz:3007", "api.n08.testnet.vega.xyz:3007", "api.n09.testnet.vega.xyz:3007", "api.n10.testnet.vega.xyz:3007", "api.n11.testnet.vega.xyz:3007", "api.n12.testnet.vega.xyz:3007"]
    Retries = 5

  [API.GraphQL]
    Hosts = ["https://api.testnet.vega.xyz/graphql", "https://api.n00.testnet.vega.xyz/graphql", "https://api.n06.testnet.vega.xyz/graphql", "https://api.n07.testnet.vega.xyz/graphql", "https://api.n08.testnet.vega.xyz/graphql", "https://api.n09.testnet.vega.xyz/graphql", "https://api.n10.testnet.vega.xyz/graphql", "https://api.n11.testnet.vega.xyz/graphql", "https://api.n12.testnet.vega.xyz/graphql"]

  [API.REST]
    Hosts = ["https://api.testnet.vega.xyz", "https://api.n00.testnet.vega.xyz", "https://api.n06.testnet.vega.xyz", "https://api.n07.testnet.vega.xyz", "https://api.n08.testnet.vega.xyz", "https://api.n09.testnet.vega.xyz", "https://api.n10.testnet.vega.xyz", "https://api.n11.testnet.vega.xyz", "https://api.n12.testnet.vega.xyz"]

[Console]
  LocalPort = 1847
  URL = ""

[TokenDApp]
  LocalPort = 1848
  URL = ""
