Name = "stagnet3"

[[Metadata]]
key = "network"
name = "stagnet3"

[API]

  [API.GRPC]
    Hosts = ["api.stagnet3.vega.xyz:3007", "api.n05.stagnet3.vega.xyz:3007", "api.n06.stagnet3.vega.xyz:3007", "api.n07.stagnet3.vega.xyz:3007"]
    Retries = 5

  [API.GraphQL]
    Hosts = ["https://api.stagnet3.vega.xyz/graphql", "https://api.n05.stagnet3.vega.xyz/graphql", "https://api.n06.stagnet3.vega.xyz/graphql", "https://api.n07.stagnet3.vega.xyz/graphql"]

  [API.REST]
    Hosts = ["https://api.stagnet3.vega.xyz", "https://api.n05.stagnet3.vega.xyz", "https://api.n06.stagnet3.vega.xyz", "https://api.n07.stagnet3.vega.xyz"]

[Apps]
  Console = "stagnet3.console.vega.xyz"
  TokenDApp = "stagnet3.governance.vega.xyz"
  Explorer = "stagnet3.explorer.vega.xyz"
