# FILE IS AUTOMATICALLY MANAGED BY github.com/vegaprotocol/terraform/github
name: "Automated network configuration update for k8s"
"on":
  # support both vega/networks & vega/networks-internal
  push:
    branches:
      - main
    paths:
      - stagnet1/vegawallet-stagnet1.toml
      - stagnet3/stagnet3.toml
      - devnet/devnet.toml
      - devnet1/vegawallet-devnet1.toml
      - fairground/vegawallet-fairground.toml
      - .github/workflows/push_network_config.yml
jobs:
  update-manifest-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VEGA_CI_SSH_KEY }}
      - run: |
          git config --global user.name 'vega-ci-bot'
          git config --global user.email 'dev@vega.xyz'
          git clone git@github.com:vegaprotocol/k8s.git

          file="stagnet1/vegawallet-stagnet1.toml"
          if [ -f $file ]; then
            echo "Updating stagnet1"
            sed -i  "1s|^|#this file is added automatically from github.com/vegaprotcol/networks-internal\n|" $file
            sed -i 's|^Host.*|Host = "0.0.0.0"|' $file
            sed -i 's|^Port.*|Port = 80|' $file
            cp $file k8s/charts/apps/vegawallet/stagnet1/files/stagnet1.toml
            cat k8s/charts/apps/vegawallet/stagnet1/files/stagnet1.toml
          fi

          file="devnet/devnet.toml"
          if [ -f $file ]; then
            echo "Updating devnet"
            sed -i  "1s|^|#this file is added automatically from github.com/vegaprotcol/networks-internal\n|" $file
            sed -i 's|^Host.*|Host = "0.0.0.0"|' $file
            sed -i 's|^Port.*|Port = 80|' $file
            cp $file k8s/charts/apps/vegawallet/devnet/files/devnet.toml
            cat k8s/charts/apps/vegawallet/devnet/files/devnet.toml
          fi

          file="devnet1/vegawallet-devnet1.toml"
          if [ -f $file ]; then
            echo "Updating devnet1"
            sed -i  "1s|^|#this file is added automatically from github.com/vegaprotcol/networks-internal\n|" $file
            sed -i 's|^Host.*|Host = "0.0.0.0"|' $file
            sed -i 's|^Port.*|Port = 80|' $file
            cp $file k8s/charts/apps/vegawallet/devnet1/files/devnet1.toml
            cat k8s/charts/apps/vegawallet/devnet1/files/devnet1.toml
          fi

          file="stagnet3/stagnet3.toml"
          if [ -f $file ]; then
            echo "Updating stagnet3"
            sed -i  "1s|^|#this file is added automatically from github.com/vegaprotcol/networks-internal\n|" $file
            sed -i 's|^Host.*|Host = "0.0.0.0"|' $file
            sed -i 's|^Port.*|Port = 80|' $file
            cp $file k8s/charts/apps/vegawallet/stagnet3/files/stagnet3.toml
            cat k8s/charts/apps/vegawallet/stagnet3/files/stagnet3.toml
          fi

          file="fairground/vegawallet-fairground.toml"
          if [ -f $file ]; then
            echo "Updating fairground"
            sed -i  "1s|^|#this file is added automatically from github.com/vegaprotcol/networks-internal\n|" $file
            sed -i 's|^Host.*|Host = "0.0.0.0"|' $file
            sed -i 's|^Port.*|Port = 80|' $file
            cp $file k8s/charts/apps/vegawallet/fairground/files/fairground.toml
            cat k8s/charts/apps/vegawallet/fairground/files/fairground.toml
          fi

          cd k8s
          if ! git diff --exit-code; then
            git add -A
            git commit -m "Automated network configuration update from repository: $GITHUB_REPOSITORY"
            git pull --rebase
            git push
          fi
